package fr.scanneat.domain.engine.nutrition

import fr.scanneat.domain.model.Ingredient

// ============================================================================
// INGREDIENT FACTS DB — the hint panel's "fun facts", solved the same way
// AdditivesDb solves "is this E-number a concern": a table of (ingredient
// name synonyms) -> one verifiable trivia line, matched by substring
// against the product's actual ingredient list.
//
// Deliberately NOT LLM-generated: a per-scan model call for one trivia line
// doesn't scale (rate limits, latency, cost) and reintroduces the exact
// hallucination risk this file's neighbour (ProductHints) was written to
// avoid.
//
// Sourced by bulk-fetching Wikipedia's REST summary API (both fr/en, one
// call per ingredient, snapshot taken 2026-07-13) rather than typed from
// memory — every fact below is that article's own opening sentence,
// trimmed, not a paraphrase, so it's directly re-verifiable against the
// live article. This is real reference-work sourcing (same category as
// citing an encyclopedia), distinct from the runtime LLM approach that
// was rejected. Still deliberately NOT exhaustive: covers ~90 of the most
// commonly scanned ingredients/spices/oils/ferments, since a wrong "fun
// fact" is worse than a missing one, and any addition should go through
// the same fetch-and-verify step rather than being hand-typed from
// recollection.
//
// Every line here is neutral encyclopedic content (taxonomy / etymology /
// food science), not a health claim — health-relevant statements belong
// in ProductHints' benefits/risks sections, cited to EFSA/WHO/IARC, not
// here.
//
// Facts are capped by the caller (see generateProductHints) to avoid
// turning the panel into a wall of trivia on a long ingredient list.
// ============================================================================

private data class IngredientFact(
    val names: List<String>,
    val factFr: String,
    val factEn: String,
)

private val FACTS: List<IngredientFact> = listOf(
    IngredientFact(listOf("cacao", "cocoa"),
        "Le cacao est le terme le plus souvent utilisé pour parler de la poudre de cacao, mais il peut être utilisé également pour parler du beurre de cacao.",
        "The cocoa bean, also known as cocoa or cacao, is the dried and fully fermented seed of Theobroma cacao, the cacao tree."),
    IngredientFact(listOf("vanille", "vanilla"),
        "La vanille est une épice constituée par le fruit de certaines orchidées lianescentes tropicales d'origine mésoaméricaine du genre Vanilla, principalement de l'espèce Vanilla planifolia.",
        "Vanilla is a spice derived from orchids of the genus Vanilla, primarily obtained from the seed pods of the flat-leaved Mexican and Central American vanilla (V. planifolia)."),
    IngredientFact(listOf("safran", "saffron"),
        "Le safran est un produit agricole classé dans la famille des épices.",
        "Saffron is a spice derived from the flower of Crocus sativus, commonly known as the \"saffron crocus\"."),
    IngredientFact(listOf("cannelle", "cinnamon"),
        "La cannelle est une épice constituée de l'écorce intérieure de certains arbres de la famille des Lauracées.",
        "Cinnamon is a spice obtained from the inner bark of several tree species from the genus Cinnamomum."),
    IngredientFact(listOf("curcuma", "turmeric"),
        "Le curcuma est une espèce de plantes herbacées rhizomateuses vivaces du genre Curcuma originaire du sud ou sud-est asiatique.",
        "Turmeric, or Curcuma longa, is a flowering plant in the ginger family Zingiberaceae."),
    IngredientFact(listOf("gingembre", "ginger"),
        "Le gingembre officinal est une espèce de plantes à fleurs originaire d'Inde et de Chine du Sud, du genre Zingiber et de la famille des Zingiberaceae dont on utilise le rhizome en cuisine et en médecine traditionnelle.",
        "Ginger is a flowering plant whose rhizome, ginger root or ginger, is widely used as a spice and a folk medicine."),
    IngredientFact(listOf("cafeine", "caffeine"),
        "La caféine, aussi désignée sous les noms de théine, 1,3,7-triméthylxanthine ou méthylthéobromine, est un alcaloïde de la famille des méthylxanthines, présent dans de nombreux aliments, qui agit comme stimulant psychotrope chez les mammifères et comme léger diurétique.",
        "Caffeine is a central nervous system (CNS) stimulant of the methylxanthine class and is the most commonly consumed psychoactive substance globally."),
    IngredientFact(listOf("grains de cafe", "coffee bean"),
        "Le café est une boisson énergisante psychotrope stimulante, obtenue à partir des graines torréfiées de diverses variétés de caféiers, des arbustes du genre Coffea.",
        "Coffee is a beverage brewed from roasted ground coffee beans."),
    IngredientFact(listOf("the vert", "green tea"),
        "Un thé vert, en chinois simplifié : 绿茶 ; chinois traditionnel : 綠茶 ; pinyin : lǜchá, et en japonais 緑茶 est un thé dont l'oxydation naturelle est rapidement stoppée après la cueillette.",
        "Green tea is a type of tea made from the leaves and buds of the Camellia sinensis that have not undergone the withering and oxidation process that creates oolong teas and black teas."),
    IngredientFact(listOf("miel", "honey"),
        "Le miel est une substance sucrée élaborée par les abeilles à miel vivant en colonies, à partir de nectar ou de miellat dont elles réduisent la teneur en eau. Elles s'en nourrissent tout au long de l'année, le stockant pour que la colonie subsiste l'hiver jusqu'au printemps suivant.",
        "Honey is a sweet and viscous substance made by several species of bees, the best-known of which are honey bees."),
    IngredientFact(listOf("huile d'olive", "olive oil"),
        "L’huile d'olive est une variété d'huile alimentaire, à base de matière grasse  végétale extraite des olives lors de la trituration dans un moulin à huile.",
        "Olive oil is a vegetable oil obtained by pressing whole olives and extracting the oil."),
    IngredientFact(listOf("huile de palme", "palm oil"),
        "L’huile de palme est une huile végétale extraite de la pulpe des fruits du palmier à huile, un arbre originaire d'Afrique tropicale dont est aussi tirée l’huile de palmiste, extraite du noyau de ses fruits.",
        "Palm oil is an edible vegetable oil derived from the reddish mesocarp (pulp) of the fruit of the African oil palm."),
    IngredientFact(listOf("huile de coco", "huile de noix de coco", "coconut oil"),
        "L’huile de coco et l'huile de coprah sont des huiles végétales fabriquées à partir de l'albumen de la noix de coco.",
        "Coconut oil is an edible oil derived from the meat of the coconut palm fruit."),
    IngredientFact(listOf("avoine", "oat", "oats"),
        "L'Avoine cultivée, parfois appelée « avoine commune », « avoine byzantine » ou simplement « avoine », est une espèce de plantes monocotylédones de la famille des Poaceae (graminées), sous-famille des Pooideae.",
        "The oat, sometimes called the common oat, is a species of cereal grass (Avena) grown for fodder and for its seed, which is known by the same name."),
    IngredientFact(listOf("quinoa"),
        "Le quinoa est une espèce de plantes herbacées annuelles de la famille des Amaranthaceae ou de celle des Chenopodiaceae.",
        "Quinoa is a flowering plant in the amaranth family."),
    IngredientFact(listOf("levure de boulanger", "levure de biere", "yeast"),
        "La levure de boulanger est une levure obtenue à partir de différentes souches de Saccharomyces cerevisiae seules ou en mélange, utilisée pour obtenir une fermentation du pain lors du processus de panification.",
        "Baker's yeast is the common name for the strains of yeast commonly used in baking bread and other bakery products, serving as a leavening agent which causes the bread to rise by converting the fermentable sugars present in the dough into carbon dioxide and ethanol."),
    IngredientFact(listOf("nori", "algue", "seaweed"),
        "Nori (海苔) désigne différentes algues rouges comestibles, utilisées dans la cuisine japonaise, notamment dans l'élaboration des makizushi et des temaki.",
        "Nori (Japanese: 海苔) is a dried edible seaweed used in Japanese cuisine, usually made from species of the red algae genus Pyropia, including P. yezoensis and P. tenera."),
    IngredientFact(listOf("canneberge", "cranberry", "cranberries"),
        "Vaccinium oxycoccos, de noms communs Canneberge ou Myrtille des marais, est une espèce de plantes de la famille des Ericaceae, du genre Vaccinium et du sous-genre Oxycoccos (Canneberges).",
        "Cranberries are a group of evergreen dwarf shrubs or trailing vines in the subgenus Oxycoccus of the genus Vaccinium."),
    IngredientFact(listOf("grenade", "pomegranate"),
        "La grenade est le fruit du grenadier de la famille des Lythracées.",
        "The pomegranate is a fruit-bearing, deciduous shrub in the family Lythraceae, subfamily Punicoideae, that grows to between 1.5–5 metres (5–16 ft) tall."),
    IngredientFact(listOf("betterave", "beetroot", "beet"),
        "La betterave potagère est une plante potagère originaire du Proche-Orient dont on cultive diverses variétés pour leur racine pivotante tubérisée et comestible, rattachées plus particulièrement à la sous-espèce Beta vulgaris subsp.",
        "Beetroot or beet is the taproot portion of a Beta vulgaris subsp."),
    IngredientFact(listOf("reglisse", "licorice", "liquorice"),
        "La réglisse ou réglisse glabre — du grec γλυκύρριζα — est une espèce de plante à fleurs de la famille des Fabacées, de la sous-famille des Faboideae, aux racines aromatiques.",
        "Liquorice or licorice is the common name of Glycyrrhiza glabra, a flowering plant of the bean family Fabaceae, from the root of which a sweet, aromatic flavouring is extracted."),
    IngredientFact(listOf("caroube", "carob"),
        "Le Caroubier est une espèce de plantes à fleurs de la famille des Légumineuses.",
        "The carob is a flowering evergreen tree or shrub in the Caesalpinioideae subfamily of the legume family, Fabaceae."),
    IngredientFact(listOf("agar-agar", "agar agar"),
        "L'agar-agar est un produit gélifiant, dont la découverte faite au Japon en 1658 par Minoya Tarozaemon est souvent attribuée à tort à Fanny et Walther Hesse, ces derniers ayant découvert en 1881 son utilité comme milieu de culture en microbiologie.",
        "Agar, or agar-agar, is a jelly-like substance consisting of polysaccharides obtained from the cell walls of some species of red algae primarily from the Gracilaria genus and the Gelidiaceae family (tengusa)."),
    IngredientFact(listOf("levure chimique", "poudre a pate", "baking powder"),
        "La levure chimique, poudre à lever, poudres levantes ou poudre à pâte est un mélange composé essentiellement d'un agent basique, un agent acide et un agent stabilisant, se présentant sous forme de poudre blanche et servant à faire gonfler pains et pâtisseries.",
        "Baking powder is a dry chemical leavening agent, a mixture of a carbonate or bicarbonate and a weak acid."),
    IngredientFact(listOf("muscade", "nutmeg"),
        "La noix de muscade est l'albumen de la graine du fruit ovoïde du muscadier, un arbre tropical de la famille des Myristicacées haut de dix à quinze mètres.",
        "Nutmeg is the seed, or the ground spice derived from the seed, of several tree species of the genus Myristica; fragrant nutmeg or true nutmeg is a dark-leaved evergreen tree cultivated for two spices derived from its fruit: nutmeg, from its seed, and mace, from the seed covering."),
    IngredientFact(listOf("girofle", "clou de girofle", "clove"),
        "Le clou de girofle est une épice obtenue à partir des boutons floraux du Giroflier de la famille des Myrtaceae et du genre Syzygium.",
        "Cloves are the aromatic flower buds of a tree in the family Myrtaceae, Syzygium aromaticum."),
    IngredientFact(listOf("cardamome", "cardamom"),
        "Le ou la Cardamome est une espèce de plantes à fleurs de la famille des Zingibéracées.",
        "Cardamom, sometimes cardamon or cardamum, is a spice made from the seeds of several plants in the genera Elettaria and Amomum in the family Zingiberaceae."),
    IngredientFact(listOf("paprika"),
        "Le paprika, aussi connu sous les termes de piment doux, poivre d'Espagne (pimentón) ou fűszerpaprika-őrlemény en Hongrie, est une épice en poudre de couleur rouge obtenue à partir du fruit mûr, séché et moulu du piment doux ou poivron.",
        "Paprika is a spice made from dried and ground red peppers, Capsicum annuum."),
    IngredientFact(listOf("cumin"),
        "Le Cumin est une espèce de plantes à fleurs de la famille des Apiacées.",
        "Cumin is a flowering plant in the family Apiaceae, native to the Irano-Turanian Region."),
    IngredientFact(listOf("basilic", "basil"),
        "Basilic peut désigner :",
        "Basil, also called great basil, is a culinary herb of the family Lamiaceae (mints)."),
    IngredientFact(listOf("romarin", "rosemary"),
        "Le Romarin, Salvia rosmarinus, est une espèce de plantes à fleurs de la famille des Lamiacées.",
        "Salvia rosmarinus, synonym Rosmarinus officinalis, commonly known as rosemary, is a shrub with fragrant, evergreen, needle-like leaves and purple or sometimes white, pink, or blue flowers."),
    IngredientFact(listOf("thym", "thyme"),
        "Thymus est un genre de plantes à fleurs de la famille des Lamiacées.",
        "Thyme is a culinary herb consisting of the dried aerial parts of some members of the genus Thymus of flowering plants in the mint family Lamiaceae."),
    IngredientFact(listOf("origan", "oregano"),
        "L’Origan ou Origan commun est une espèce de plantes à fleurs de la famille des Lamiacées.",
        "Oregano is a species of flowering plant in the mint family, Lamiaceae."),
    IngredientFact(listOf("menthe", "mint"),
        "Les menthes (Mentha) sont un genre de plantes à fleurs de la tribu des Mentheae.",
        "Mint or The Mint may refer to:"),
    IngredientFact(listOf("sesame", "tahini"),
        "Le sésame est une espèce de plantes à fleurs de la famille des Pédaliacées.",
        "Sesame is a plant in the genus Sesamum, also called benne."),
    IngredientFact(listOf("amande", "almond"),
        "L'amande est le fruit de l'amandier.",
        "The almond is a species of tree from the genus Prunus."),
    IngredientFact(listOf("noisette", "hazelnut"),
        "La noisette est le fruit du noisetier commun (Corylus avellana), ainsi que de diverses espèces voisines du genre Corylus.",
        "The hazelnut is the fruit of the hazel tree and therefore includes any of the nuts deriving from species of the genus Corylus, especially the nuts of the species Corylus avellana."),
    IngredientFact(listOf("noix"),
        "La noix est un fruit comestible à coque.",
        "A walnut is the edible seed of any tree of the genus Juglans, particularly the Persian or English walnut, Juglans regia."),
    IngredientFact(listOf("noix de cajou", "cajou", "cashew"),
        "La noix de cajou ou anacarde est la graine contenue dans la pomme de cajou, le fruit de l'anacardier, arbre originaire d’Amérique tropicale.",
        "Cashew is the common name of a tropical evergreen tree Anacardium occidentale, in the family Anacardiaceae."),
    IngredientFact(listOf("pistache", "pistachio"),
        "La pistache est un fruit sec, produit par le pistachier vrai, arbuste de la famille des Anacardiacées.",
        "The pistachio is a small to medium-sized tree of the cashew family."),
    IngredientFact(listOf("chia"),
        "La chia, prononcé /ˈt͡ʃi.a/, est une espèce de plantes à fleurs de la famille des Lamiacées.",
        "Chia seeds are the edible seeds of Salvia hispanica, a flowering plant in the mint family (Lamiaceae) native to central and southern Mexico, or of the related Salvia columbariae, Salvia polystachia, or Salvia tiliifolia."),
    IngredientFact(listOf("graine de lin", "lin", "flaxseed", "linseed"),
        "La graine de lin est une graine oléagineuse, produite par le lin cultivé consommée par les humains depuis le Néolithique.",
        "Flax, also known as common flax or line, is a flowering plant, Linum usitatissimum, in the family Linaceae."),
    IngredientFact(listOf("sirop d'erable", "maple syrup"),
        "Le sirop d’érable est une solution naturellement sucrée, fabriquée à partir d'eau d'érable recueillie au début du printemps et concentrée par osmose inverse et ébullition.",
        "Maple syrup is a sweet syrup made from the sap of maple trees."),
    IngredientFact(listOf("sirop d'agave", "agave"),
        "Le sirop d'agave est un édulcorant produit à partir de plusieurs espèces d'agaves dont Agave tequilana.",
        "Agave syrup, also known as maguey syrup or agave nectar, is a sweetener commercially produced from several species of agave, including Agave tequilana and Agave salmiana."),
    IngredientFact(listOf("melasse", "molasses"),
        "La mélasse est un liquide visqueux incristallisable résultant du raffinage du sucre extrait de la betterave sucrière ou de la canne à sucre.",
        "Molasses is a viscous byproduct principally obtained from the refining of sugarcane or sugar beet juice into sugar."),
    IngredientFact(listOf("vinaigre balsamique", "balsamic"),
        "Le vinaigre balsamique ou balsamique désigne une grande variété de vinaigres de la cuisine italienne, historiquement à base de moût de raisin cuit (vincotto) et plus récemment, selon les appellations, pouvant inclure éventuellement d'autres vinaigres, également dits balsamiques ou non, et d'autres composants.",
        "Balsamic vinegar is a dark, concentrated, pungent, intensely flavoured vinegar made wholly or partially from grape must, which is freshly crushed grape juice with all the skins, seeds, and stems."),
    IngredientFact(listOf("sauce soja", "soy sauce", "shoyu"),
        "La sauce de soja ou sauce soja, appelée sauce (de) soya au Canada, soyo en Nouvelle-Calédonie ou encore siave à La Réunion, est une sauce d'origine chinoise utilisée principalement dans la cuisine asiatique d'Extrême-Orient, produite par fermentation de protéines végétales.",
        "Soy sauce is a liquid condiment of Chinese origin, traditionally made from a fermented paste of soybeans, roasted grain, brine, and Aspergillus oryzae or Aspergillus sojae molds (kōji)."),
    IngredientFact(listOf("miso"),
        "Le miso (味噌, prononcé en japonais : /mi.so/), est un aliment japonais traditionnel qui se présente sous forme de pâte fermentée, à haute teneur en protéines, de goût plus ou moins prononcé selon la fermentation et relativement salé.",
        "Miso  is a traditional Japanese seasoning."),
    IngredientFact(listOf("tempeh"),
        "Le tempeh est un produit alimentaire traditionnel à base de soja fermenté, originaire d'Indonésie.",
        "Tempeh or tempe is a traditional Indonesian food made from fermented soybeans."),
    IngredientFact(listOf("kombucha"),
        "Le kombucha est une boisson fermentée légèrement acide, d'origine chinoise.",
        "Kombucha is a fermented, effervescent and sweetened black tea drink."),
    IngredientFact(listOf("kimchi"),
        "Le kimchi, composé principalement de chou chinois, est un mets traditionnel coréen composé de piments et de légumes lacto-fermentés, c'est-à-dire trempés dans de la saumure pendant plusieurs semaines jusqu'au développement d'une acidité.",
        "Kimchi is a traditional Korean side dish (banchan) consisting of salted and fermented vegetables, most often napa cabbage or Korean radish."),
    IngredientFact(listOf("choucroute", "sauerkraut"),
        "La choucroute est un mets composé de chou coupé finement et transformé par lacto-fermentation dans une saumure généralement accompagné de garniture.",
        "Sauerkraut is finely cut raw white cabbage that has been fermented by various lactic acid bacteria."),
    IngredientFact(listOf("tofu"),
        "Le tofu, aussi écrit tofou et appelé fromage de soja est un aliment d'origine chinoise issu de la coagulation de boisson végétale à base de soja.",
        "Tofu  or bean curd is a food prepared by pressing the curds of coagulated soy milk into solid white blocks of varying softness: 'silken', 'soft', 'firm', and 'extra firm'."),
    IngredientFact(listOf("seitan"),
        "Le seitan est une spécialité à base de farine de blé ou d'épeautre, dont ont été extraits l'amidon et le son afin de ne laisser que le gluten.",
        "Seitan is a food made from gluten, the main protein of wheat."),
    IngredientFact(listOf("levure alimentaire", "nutritional yeast", "levure maltee"),
        "Les levures alimentaires sont des levures de différents types, utilisées dans l'alimentation animale et humaine.",
        "Nutritional yeast is a deactivated yeast, often a strain of Saccharomyces cerevisiae, that is sold commercially as a food product."),
    IngredientFact(listOf("spiruline", "spirulina"),
        "Spiruline est un nom vernaculaire ambigu en français, pouvant désigner plusieurs espèces différentes de cyanobactéries filamenteuses originaires des eaux chaudes peu profondes et saumâtres de la ceinture intertropicale.",
        "Spirulina may refer to:"),
    IngredientFact(listOf("matcha"),
        "Le matcha (抹茶, litt.",
        "Matcha is a finely ground powder of green tea specially processed from shade-grown tea leaves."),
    IngredientFact(listOf("chicoree", "chicory"),
        "Les chicorées (Cichorium) sont un genre de plantes à fleurs dicotylédones de la famille des Asteraceae (composées), sous-famille des Cichorioideae, originaire de l'Ancien Monde, qui compte six espèces acceptées, dont deux sont cultivées et quatre espèces sauvages.",
        "Common chicory is a somewhat woody, perennial herbaceous plant of the family Asteraceae, usually with bright blue flowers, rarely white or pink."),
    IngredientFact(listOf("gomme xanthane", "xanthan"),
        "La gomme xanthane est un polyoside obtenu à partir de l'action d'une bactérie, la Xanthomonas campestris.",
        "Xanthan gum is a polysaccharide with many industrial uses, including as a common food additive."),
    IngredientFact(listOf("gomme de guar", "guar"),
        "La gomme de guar est un polysaccharide à galactomannane extrait de la graine du haricot de guar, Cyamopsis tetragonoloba, plante annuelle de la famille des Fabaceae.",
        "Guar gum, also called guaran, is a galactomannan polysaccharide extracted from guar beans that has thickening and stabilizing properties useful in food, feed, and industrial applications."),
    IngredientFact(listOf("pectine", "pectin"),
        "Les pectines, ou plus largement les substances pectiques, sont des polyosides, rattachées aux glucides.",
        "Pectin is a heteropolysaccharide, a structural polymer contained in the cell walls and middle lamellae of terrestrial plants."),
    IngredientFact(listOf("gelatine", "gelatin"),
        "La gélatine est une substance solide translucide, transparente ou légèrement jaune, presque sans goût et sans odeur, obtenue par l'ébullition prolongée de tissus conjonctifs (peaux) ou d'os d'animaux.",
        "Gelatin in American English or gelatine in British English is a translucent, colorless, flavorless food ingredient, commonly derived from collagen taken from animal body parts."),
    IngredientFact(listOf("presure", "rennet"),
        "La présure est un coagulant du lait d'origine animale extrait de la caillette de jeunes ruminants après l’abattage.",
        "Rennet is a complex set of enzymes produced in the stomachs of ruminant mammals."),
    IngredientFact(listOf("lactoserum", "petit-lait", "whey"),
        "Le lactosérum, également appelé petit-lait bien que cette appellation puisse donner lieu à confusion, ou sérum, est la partie liquide résiduelle de la coagulation du lait.",
        "Whey is the liquid remaining after milk has been curdled and strained."),
    IngredientFact(listOf("babeurre", "buttermilk"),
        "Le babeurre ou lait de baratte, lait ribot, lait battu, lait de beurre est, au sens strict, un liquide blanc obtenu lors de la fabrication du beurre par barattage de crème de lait.",
        "Buttermilk is a dairy drink made by adding lactic acid bacteria to milk to produce a fermented dairy drink."),
    IngredientFact(listOf("ghee"),
        "Le ghi ou ghee est un beurre clarifié, originaire du sous-continent indien, que l'on retrouve également dans les cuisines arabes, notamment la cuisine levantine, égyptienne ou encore maghrébine.",
        "Ghee is a type of clarified butter, originating in the Indian Subcontinent."),
    IngredientFact(listOf("tahin", "tahini"),
        "Le tahini, tahin, tahina, téhina ou tahiné, est une crème orientale de graines de sésame.",
        "Tahini is a Middle Eastern condiment made from ground sesame seeds."),
    IngredientFact(listOf("houmous", "hummus"),
        "Le houmous ou hommos est une préparation culinaire du Proche-Orient, composée notamment de purée de pois chiches et de tahini.",
        "Hummus is a Levantine dip, spread, or savory dish made from cooked, mashed chickpeas blended with tahini, lemon juice, and garlic."),
    IngredientFact(listOf("truffe"),
        "La truffe est le nom vernaculaire français donné à la fructification et à l'organe végétatif de plusieurs genres de champignons hypogés ascomycètes ectomycorhiziens qui se présente sous une forme plus ou moins globuleuse.",
        "A truffle is the fruiting body of a subterranean ascomycete fungus, one of the species of the genus Tuber."),
    IngredientFact(listOf("shiitake"),
        "Le Lentin du Chêne, Lentin comestible, Shiitake, Shiitaké, ou encore Champignon parfumé, est une espèce de champignons basidiomycètes de la famille des Marasmiaceae.",
        "The shiitake is a macrofungus native to East Asia and mainland Southeast Asia, which is cultivated and consumed around the globe."),
    IngredientFact(listOf("wasabi"),
        "Le wasabi (山葵, prononcé en japonais : /waꜜsabi/, litt.",
        "Wasabi or Japanese horseradish is a plant of the family Brassicaceae, which also includes horseradish and mustard in other genera."),
    IngredientFact(listOf("anis etoile", "badiane", "star anise"),
        "La badiane chinoise, ou anis étoilé, est le fruit du badianier de Chine (Illicium verum), utilisée comme épice en cuisine pour son goût anisé.",
        "Illicium verum is a medium-sized evergreen tree native to South China and northeast Vietnam."),
    IngredientFact(listOf("fenouil", "fennel"),
        "Fenouil est un nom vernaculaire ambigu désignant, en français, une multitude de plantes de genres divers, notamment de la famille des Apiaceae.",
        "Fennel is a flowering plant species in the carrot family."),
    IngredientFact(listOf("coriandre", "cilantro", "coriander"),
        "La coriandre ou coriandre cultivée est une espèce de plantes à fleurs de la famille des Apiacées (Ombellifères).",
        "Coriander, or Coriandrum sativum, is an annual herb in the family Apiaceae."),
    IngredientFact(listOf("zaatar", "za'atar"),
        "Le zaatar désigne principalement un mélange d'épices traditionnel de la cuisine levantine.",
        "Za'atar is a versatile herb blend and family of wild herbs native to the Levant, central to Middle Eastern cuisine and culture."),
    IngredientFact(listOf("harissa"),
        "La harissa ou l'harissa est une purée de piments rouges originaire de Tunisie.",
        "Harissa is a Tunisian hot chili pepper paste."),
    IngredientFact(listOf("sriracha"),
        "La sauce sriracha est un type de sauce piquante thaïlandaise, nommée d'après la ville côtière de Si Racha, dans la province de Chonburi, d'où elle est originaire.",
        "Sriracha is a type of hot sauce or chili sauce made from a paste of chili peppers, distilled vinegar, pickled garlic, sugar, and salt."),
    IngredientFact(listOf("worcestershire"),
        "La sauce Worcestershire est un condiment d'origine anglaise, à la saveur aigre-douce et légèrement piquante, inventé en 1837 par la compagnie Lea & Perrins (en).",
        "Worcestershire sauce or Worcester sauce is a fermented condiment invented by the pharmacists John Wheeley Lea and William Henry Perrins in Worcester, Worcestershire, England, during the first half of the 19th century."),
    IngredientFact(listOf("moutarde de dijon"),
        "La moutarde de Dijon est une moutarde traditionnelle de la cuisine française, originaire de la ville de Dijon en Bourgogne.",
        "Dijon mustard is a traditional mustard from France."),
    IngredientFact(listOf("capre", "capers", "caper"),
        "La câpre est un condiment produit à partir de boutons floraux du câprier commun ainsi que du câprier ovale.",
        "Capparis spinosa, the caper bush, also called Flinders rose, is a perennial plant that bears rounded, fleshy leaves and large white to pinkish-white flowers."),
    IngredientFact(listOf("anchois", "anchovy"),
        "Les anchois ou engraulidés (Engraulidae) forment une famille de poissons dont de nombreuses espèces sont consommées par l'homme et les animaux marins.",
        "Anchovies are small, common forage fish of the family Engraulidae."),
    IngredientFact(listOf("parmesan"),
        "Le Parmigiano Reggiano, ou parmesan, est un fromage italien à pâte pressée cuite de la famille grana, produit avec du lait de vache, partiellement écrémé par surfaçage, sans ajout d'additifs, fabriqué dans une zone limitée de l'Émilie-Romagne, au sud de la Lombardie.",
        "Parmesan is an Italian hard, granular cheese produced from cow's milk and aged at least 12 months."),
    IngredientFact(listOf("roquefort"),
        "Le roquefort, ou ròcafòrt en occitan rouergat, est un fromage à pâte persillée élaboré dans le sud de la France exclusivement avec des laits crus de brebis.",
        "Roquefort is a sheep-milk blue cheese from southern France."),
    IngredientFact(listOf("mozzarella"),
        "La mozzarella ou mozzarelle est un fromage à pâte filée traditionnel de la cuisine italienne, à base de lait de vache ou de bufflonne.",
        "Mozzarella is a semi-soft non-aged cheese prepared using the pasta filata ('stretched-curd') method."),
    IngredientFact(listOf("feta"),
        "Feta ou féta désigne un fromage caillé en saumure originaire de Grèce.",
        "Feta is a Greek brined white cheese made from sheep's milk or from a mixture of sheep and goat's milk."),
    IngredientFact(listOf("levain"),
        "Le levain naturel est une flore microbienne destinée à produire une fermentation dans laquelle interagissent principalement des bactéries lactiques, majoritaires, ainsi que des levures et moisissures.",
        "Sourdough is a leavening agent containing naturally occurring yeast and lactobacillus bacteria."),
    IngredientFact(listOf("camembert"),
        "Camembert est une appellation générique qui désigne généralement un fromage à pâte molle et à croûte fleurie.",
        "Camembert is a moist, soft, creamy, surface-ripened cow's milk cheese."),
    IngredientFact(listOf("ail", "garlic"),
        "L'ail, ail commun ou ail cultivé est une espèce de plantes potagères vivaces monocotylédones dont les bulbes, à l'odeur et au goût forts, sont souvent employés comme condiment en cuisine.",
        "Allium sativum, commonly known as garlic, is a species of bulbous flowering plant in the genus Allium."),
    IngredientFact(listOf("sumac"),
        "Le nom sumac désigne en français diverses espèces de plantes appartenant principalement à la famille des Anacardiaceae.",
        "Sumac or sumach is any of about 35 species of flowering plants in the genus Rhus and related genera, in the family Anacardiaceae."),
)

/**
 * Match the product's ingredient names against the curated facts table.
 * Returns at most [limit] facts, in ingredient-list order, de-duplicated
 * (an ingredient list mentioning both "cacao" and "chocolat noir" should
 * only surface the cocoa fact once).
 */
fun findIngredientFacts(ingredients: List<Ingredient>, lang: String, limit: Int = 3): List<String> {
    val en = lang == "en"
    return matchIngredientDictionary(ingredients, FACTS, IngredientFact::names, limit)
        .map { if (en) it.factEn else it.factFr }
}
