package fr.scanneat.data.local.db

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import fr.scanneat.data.local.db.activity.ActivityDao
import fr.scanneat.data.local.db.activity.ActivityEntity
import fr.scanneat.data.local.db.consumption.ConsumptionDao
import fr.scanneat.data.local.db.consumption.ConsumptionEntity
import fr.scanneat.data.local.db.customfood.CustomFoodDao
import fr.scanneat.data.local.db.customfood.CustomFoodEntity
import fr.scanneat.data.local.db.medication.MedicationDao
import fr.scanneat.data.local.db.medication.MedicationEntity
import fr.scanneat.data.local.db.recipe.RecipeDao
import fr.scanneat.data.local.db.recipe.RecipeEntity
import fr.scanneat.data.local.db.scan.ScanHistoryDao
import fr.scanneat.data.local.db.scan.ScanHistoryEntity
import fr.scanneat.data.local.db.template.MealTemplateDao
import fr.scanneat.data.local.db.template.MealTemplateEntity
import fr.scanneat.data.local.db.weight.WeightDao
import fr.scanneat.data.local.db.weight.WeightEntity

@Database(
    entities = [
        ScanHistoryEntity::class,
        ConsumptionEntity::class,
        CustomFoodEntity::class,
        WeightEntity::class,
        ActivityEntity::class,
        MealTemplateEntity::class,
        RecipeEntity::class,
        MedicationEntity::class,
    ],
    version = 13,
    exportSchema = true,
)
@TypeConverters(Converters::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun scanHistoryDao(): ScanHistoryDao
    abstract fun consumptionDao(): ConsumptionDao
    abstract fun customFoodDao(): CustomFoodDao
    abstract fun weightDao(): WeightDao
    abstract fun activityDao(): ActivityDao
    abstract fun mealTemplateDao(): MealTemplateDao
    abstract fun recipeDao(): RecipeDao
    abstract fun medicationDao(): MedicationDao
}

// ── Room migrations ────────────────────────────────────────────────────────────
// Add a new Migration object for each schema version bump before shipping.
// Schema versions are defined on @Database(version = N).
//
// exportSchema = true writes JSON snapshots to app/schemas/ (ksp arg
// room.schemaLocation, app/build.gradle.kts) on every build, but no schemas/
// directory has ever been committed to this repo (not gitignored — just never
// generated by a build whose output got checked in). Room's own migration
// testing (androidx.room:room-testing MigrationTestHelper) needs those
// historical schema JSONs to validate a migration against the real prior
// schema; without them, MIGRATION_4_5 and MIGRATION_5_6 above have never been
// verified against anything but manual reading. Generate once via a local/CI
// build with Android SDK access and commit app/schemas/ — this sandbox has
// neither, so it can't be done from here (see QUEUE.md).
val MIGRATION_1_2 = object : Migration(1, 2) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // v1 → v2: initial schema (no changes required — baseline)
    }
}
val MIGRATION_2_3 = object : Migration(2, 3) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // v2 → v3: added RecipeEntity. This was previously a no-op comment, which
        // meant Room used this (empty) registered migration instead of falling back
        // to fallbackToDestructiveMigration() — anyone upgrading from a v2 install
        // hit "no such table: recipes" the moment Recipes/Grocery/Templates opened.
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `recipes` (" +
                "`id` TEXT NOT NULL, " +
                "`name` TEXT NOT NULL, " +
                "`servings` INTEGER NOT NULL, " +
                "`componentsJson` TEXT NOT NULL, " +
                "`createdAt` INTEGER NOT NULL, " +
                "`profileId` TEXT NOT NULL, " +
                "PRIMARY KEY(`id`))"
        )
    }
}
val MIGRATION_3_4 = object : Migration(3, 4) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // v3 → v4: add indices to the two tables that grow largest over time.
        // Without these, observeRecent/findByBarcode (run on every scan) and
        // observeByDate/observeRange (run on every Diary/Dashboard load) do a full
        // table scan — fine with a handful of rows, a real slowdown after months of use.
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_scan_history_profileId_scannedAt` ON `scan_history` (`profileId`, `scannedAt`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_scan_history_barcode_profileId` ON `scan_history` (`barcode`, `profileId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_consumption_log_profileId_date` ON `consumption_log` (`profileId`, `date`)")
    }
}
val MIGRATION_4_5 = object : Migration(4, 5) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // v4 → v5: favorite flag on scan_history, so a specific scan can be
        // pinned and found again from a dedicated Favorites filter.
        db.execSQL("ALTER TABLE `scan_history` ADD COLUMN `favorite` INTEGER NOT NULL DEFAULT 0")
    }
}
val MIGRATION_5_6 = object : Migration(5, 6) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // v5 → v6: weight_log's unique index was on `date` alone, not
        // `(date, profileId)` — a second profile logging on a date the
        // first already has would silently REPLACE-delete the first
        // profile's row. Not reachable today (no UI ever passes a
        // non-"default" profileId yet) but free to fix before any real
        // dual-profile data exists.
        db.execSQL("DROP INDEX IF EXISTS `index_weight_log_date`")
        db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS `index_weight_log_date_profileId` ON `weight_log` (`date`, `profileId`)")
    }
}
val MIGRATION_6_7 = object : Migration(6, 7) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // v6 → v7: activity_log was the one remaining table indexed on
        // `date` alone instead of `(date, profileId)` like
        // consumption_log/scan_history already are - a non-unique lookup
        // index, so no data-loss risk like weight_log's v5→v6 fix, just a
        // consistency/query-shape gap that will matter once multi-profile
        // queries are actually reachable.
        db.execSQL("DROP INDEX IF EXISTS `index_activity_log_date`")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_activity_log_date_profileId` ON `activity_log` (`date`, `profileId`)")
    }
}
val MIGRATION_7_8 = object : Migration(7, 8) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // v7 → v8: observeFavorites' WHERE profileId = ? AND favorite = 1 ORDER BY
        // scannedAt DESC wasn't covered by either existing scan_history index (one
        // leads with scannedAt, the other with barcode) - full table scan on every
        // emission of a Flow that's held live for the whole history screen.
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_scan_history_profileId_favorite_scannedAt` ON `scan_history` (`profileId`, `favorite`, `scannedAt`)")
    }
}
val MIGRATION_8_9 = object : Migration(8, 9) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // v8 → v9: custom_foods/recipes/meal_templates all filter WHERE
        // profileId = ? but, unlike every other user-content table, had no
        // index backing it - the same full-table-scan gap v3→v4 fixed for
        // scan_history/consumption_log.
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_custom_foods_profileId` ON `custom_foods` (`profileId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_recipes_profileId` ON `recipes` (`profileId`)")
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_meal_templates_profileId` ON `meal_templates` (`profileId`)")
    }
}
val MIGRATION_9_10 = object : Migration(9, 10) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // v9 → v10: activity_log gains an optional sub-type (e.g. "bench_press"
        // under STRENGTH, "trail" under RUNNING) plus free-form training metrics
        // (sets/reps/distance/weight used) - Activité previously had only a flat
        // activity-type + duration, with no way to record what was actually done.
        db.execSQL("ALTER TABLE `activity_log` ADD COLUMN `subType` TEXT")
        db.execSQL("ALTER TABLE `activity_log` ADD COLUMN `sets` INTEGER")
        db.execSQL("ALTER TABLE `activity_log` ADD COLUMN `reps` INTEGER")
        db.execSQL("ALTER TABLE `activity_log` ADD COLUMN `distanceKm` REAL")
        db.execSQL("ALTER TABLE `activity_log` ADD COLUMN `weightUsedKg` REAL")
    }
}
val MIGRATION_10_11 = object : Migration(10, 11) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // v10 → v11: new `medications` table backing the Traitement tab -
        // manual medication tracking (name/dosage/schedule note/active flag),
        // same shape as every other user-content table.
        db.execSQL(
            "CREATE TABLE IF NOT EXISTS `medications` (" +
                "`id` TEXT NOT NULL, " +
                "`name` TEXT NOT NULL, " +
                "`dosage` TEXT NOT NULL, " +
                "`scheduleNote` TEXT NOT NULL, " +
                "`barcode` TEXT, " +
                "`active` INTEGER NOT NULL, " +
                "`createdAt` INTEGER NOT NULL, " +
                "`profileId` TEXT NOT NULL, " +
                "PRIMARY KEY(`id`))"
        )
        db.execSQL("CREATE INDEX IF NOT EXISTS `index_medications_profileId` ON `medications` (`profileId`)")
    }
}
val MIGRATION_11_12 = object : Migration(11, 12) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // v11 → v12: medications gain an optional daily reminder — Fasting/
        // Hydration/Weight all fire a notification via ReminderWorker, but a
        // medication's "schedule" was just a display-only free-text note with
        // no way to actually be reminded to take it.
        db.execSQL("ALTER TABLE `medications` ADD COLUMN `reminderOn` INTEGER NOT NULL DEFAULT 0")
        db.execSQL("ALTER TABLE `medications` ADD COLUMN `reminderTime` TEXT NOT NULL DEFAULT '08:00'")
    }
}
val MIGRATION_12_13 = object : Migration(12, 13) {
    override fun migrate(db: SupportSQLiteDatabase) {
        // v12 → v13: activity_log gains an optional externalSourceId - Health
        // Connect sync for Activité was write-only (mirrors a logged workout
        // out), same as it was for weight before weight got a read-back sync.
        // A workout logged by an external fitness tracker straight into Health
        // Connect could never be pulled into Scan'eat's own history. This
        // column is the dedup key: without a stable id to check against,
        // re-running the sync would re-import the same external session as a
        // fresh duplicate every time (activity, unlike weight, has no
        // one-entry-per-day convention to dedupe against instead).
        db.execSQL("ALTER TABLE `activity_log` ADD COLUMN `externalSourceId` TEXT")
    }
}
