package fr.scanneat.domain.engine.scoring

// ============================================================================
// ADDITIVES DATABASE — Tier 3 (minor/contextual), core set.
// Split out of AdditivesDb.kt; concatenated into ADDITIVES_DB there.
// Source citations preserved verbatim from the original TS engine.
// ============================================================================

internal val ADDITIVES_TIER3_CORE: List<AdditiveInfo> = listOf(
    AdditiveInfo("E407", listOf("carraghénane", "carrageenan"), AdditiveTier.THREE, AdditiveCategory.THICKENER,
        "EFSA reaffirmed safety at use levels; animal inflammation signals not replicated at dietary doses.", "EFSA 2018;16(4):5238."),
    AdditiveInfo("E471", listOf("mono- et diglycérides d'acides gras"), AdditiveTier.THREE, AdditiveCategory.EMULSIFIER,
        "Ubiquitous emulsifier; tier reflects UPF-class marker, not direct concern.", "EFSA 2017;15(11):5045."),
    AdditiveInfo("E472", listOf("esters de mono- et diglycérides", "esters of monoglycerides"), AdditiveTier.THREE, AdditiveCategory.EMULSIFIER,
        "Family of emulsifiers; no numerical ADI.", "EFSA 2017;15(11):5045 (group with E471)."),
    AdditiveInfo("E621", listOf("glutamate monosodique", "monosodium glutamate", "msg"), AdditiveTier.THREE, AdditiveCategory.FLAVOR_ENHANCER,
        "EFSA derived group ADI 2017 out of caution; JECFA maintains safe.", "EFSA 2017;15(7):4910."),
    AdditiveInfo("E627", listOf("guanylate disodique", "disodium guanylate"), AdditiveTier.THREE, AdditiveCategory.FLAVOR_ENHANCER,
        "Nucleotide flavour enhancer; UPF flavour engineering signal.", "EFSA 2017;15(7):4910."),
    AdditiveInfo("E631", listOf("inosinate disodique", "disodium inosinate"), AdditiveTier.THREE, AdditiveCategory.FLAVOR_ENHANCER,
        "Nucleotide flavour enhancer; often animal-derived (relevant for vegetarians).", "EFSA 2017;15(7):4910."),
    AdditiveInfo("E635", listOf("ribonucléotides disodiques", "disodium ribonucleotides"), AdditiveTier.THREE, AdditiveCategory.FLAVOR_ENHANCER,
        "Mix of E631/E627; same context.", "EFSA 2017;15(7):4910."),
    AdditiveInfo("E316", listOf("érythorbate de sodium", "sodium erythorbate"), AdditiveTier.THREE, AdditiveCategory.ANTIOXIDANT,
        "Vitamin C isomer; often co-signals nitrite curing system.", "EFSA 2015 (ascorbic acid family)."),
    AdditiveInfo("E330", listOf("acide citrique", "citric acid"), AdditiveTier.THREE, AdditiveCategory.ACIDULANT,
        "Ubiquitous acidulant; no authoritative concern.", "EU authorisation without ADI."),
    AdditiveInfo("E300", listOf("acide ascorbique", "ascorbic acid", "vitamine c"), AdditiveTier.THREE, AdditiveCategory.ANTIOXIDANT,
        "Vitamin C antioxidant; no concern.", "EU authorisation without ADI."),
    AdditiveInfo("E322", listOf("lécithine", "lecithines", "lecithin", "lécithine de soja", "lécithine de tournesol"), AdditiveTier.THREE, AdditiveCategory.EMULSIFIER,
        "Phospholipid emulsifier; tier reflects formulation marker role.", "EFSA 2017;15(4):4742."),
    AdditiveInfo("E415", listOf("gomme xanthane", "xanthan gum"), AdditiveTier.THREE, AdditiveCategory.THICKENER,
        "Microbial polysaccharide; EFSA confirmed no concern.", "EFSA 2017;15(2):4712."),
    AdditiveInfo("E412", listOf("gomme guar", "guar gum"), AdditiveTier.THREE, AdditiveCategory.THICKENER,
        "Legume-derived soluble fibre; no concern.", "EFSA 2017;15(2):4669."),
    AdditiveInfo("E440", listOf("pectine", "pectines", "pectin"), AdditiveTier.THREE, AdditiveCategory.THICKENER,
        "Natural plant fibre; no concern.", "EFSA 2017;15(7):4874."),
    AdditiveInfo("E202", listOf("sorbate de potassium", "potassium sorbate"), AdditiveTier.THREE, AdditiveCategory.PRESERVATIVE,
        "Mould/yeast preservative; low concern.", "EFSA 2019;17(3):5626."),
    AdditiveInfo("E270", listOf("acide lactique", "lactic acid"), AdditiveTier.THREE, AdditiveCategory.ACIDULANT,
        "Naturally occurring metabolite; no concern.", "EU authorisation without ADI."),
    AdditiveInfo("E296", listOf("acide malique", "malic acid"), AdditiveTier.THREE, AdditiveCategory.ACIDULANT,
        "Naturally occurring fruit acid; no concern.", "EU authorisation without ADI."),
    AdditiveInfo("E500", listOf("bicarbonate de sodium", "sodium bicarbonate", "carbonate de sodium"), AdditiveTier.THREE, AdditiveCategory.ACIDITY_REGULATOR,
        "Leavening agent; no concern.", "EU authorisation without ADI."),
    AdditiveInfo("E551", listOf("dioxyde de silicium", "silicon dioxide", "silice"), AdditiveTier.THREE, AdditiveCategory.ANTICAKING,
        "Anti-caking; EFSA 2018 requested more data on nanoparticulate forms.", "EFSA 2018;16(1):5088."),
    AdditiveInfo("E422", listOf("glycérol", "glycerol", "glycérine"), AdditiveTier.THREE, AdditiveCategory.HUMECTANT,
        "Metabolised like a carbohydrate; no ADI specified.", "EU authorisation without ADI."),
    AdditiveInfo("E960", listOf("glycosides de stéviol", "steviol glycosides", "stévia", "stevia"), AdditiveTier.THREE, AdditiveCategory.SWEETENER,
        "Plant-derived non-nutritive sweetener; lower concern than artificial.", "EFSA 2010;8(4):1537."),
    AdditiveInfo("E100", listOf("curcumine", "curcuma (colorant)"), AdditiveTier.THREE, AdditiveCategory.COLORANT,
        "Natural colorant; cosmetic-processing signal.", "EFSA 2010;8(9):1679."),
    AdditiveInfo("E160a", listOf("caroténoïdes", "beta-carotène", "beta carotene", "carotenes"), AdditiveTier.THREE, AdditiveCategory.COLORANT,
        "Carotenoid; EFSA caution at very high supplemental intakes, not at food-additive use.", "EFSA 2012;10(3):2593."),
    AdditiveInfo("E160c", listOf("paprika (colorant)", "extrait de paprika", "oléorésine de paprika"), AdditiveTier.THREE, AdditiveCategory.COLORANT,
        "Natural colorant; cosmetic-processing signal.", "EFSA 2015;13(12):4320."),
    AdditiveInfo("E163", listOf("anthocyanes", "anthocyanins", "extrait de peau de raisin"), AdditiveTier.THREE, AdditiveCategory.COLORANT,
        "Anthocyanin colorants; generally safe.", "EFSA 2013;11(4):3145."),
    AdditiveInfo("E170", listOf("carbonate de calcium", "calcium carbonate"), AdditiveTier.THREE, AdditiveCategory.COLORANT,
        "White colorant + acidity regulator + calcium carrier; no concern.", "EFSA 2011;9(7):2318."),
    AdditiveInfo("E101", listOf("riboflavine", "riboflavin", "vitamine b2"), AdditiveTier.THREE, AdditiveCategory.COLORANT,
        "Vitamin B2 colorant; tier reflects cosmetic-processing signal.", "EFSA 2013;11(10):3357."),
    AdditiveInfo("E150a", listOf("e150a", "caramel ordinaire", "plain caramel"), AdditiveTier.THREE, AdditiveCategory.COLORANT,
        "Plain caramel; no 4-MEI concern.", "EFSA 2011;9(3):2004."),
    AdditiveInfo("E150b", listOf("e150b", "caramel caustique", "caustic-sulfite caramel"), AdditiveTier.THREE, AdditiveCategory.COLORANT,
        "Caustic-sulfite caramel; no 4-MEI concern.", "EFSA 2011;9(3):2004."),
    AdditiveInfo("E260", listOf("acide acétique", "acetic acid"), AdditiveTier.THREE, AdditiveCategory.ACIDULANT,
        "Acetic acid (vinegar); long history of safe use.", "EU authorisation (quantum satis)."),
    AdditiveInfo("E325", listOf("lactate de sodium", "sodium lactate"), AdditiveTier.THREE, AdditiveCategory.PRESERVATIVE,
        "Common in deli meats; authorised without ADI.", "EU Regulation 1333/2008 Annex II."),
    AdditiveInfo("E327", listOf("lactate de calcium", "calcium lactate"), AdditiveTier.THREE, AdditiveCategory.PRESERVATIVE,
        "Acidity regulator + calcium fortifier.", "EU Regulation 1333/2008 Annex II."),
    AdditiveInfo("E331", listOf("citrate de sodium", "sodium citrate"), AdditiveTier.THREE, AdditiveCategory.ACIDITY_REGULATOR,
        "Citrate buffer; no concern.", "EU authorisation without ADI."),
    AdditiveInfo("E332", listOf("citrate de potassium", "potassium citrate"), AdditiveTier.THREE, AdditiveCategory.ACIDULANT,
        "Citrate buffer; no concern.", "EU authorisation without ADI."),
    AdditiveInfo("E333", listOf("citrate de calcium", "calcium citrate"), AdditiveTier.THREE, AdditiveCategory.ACIDITY_REGULATOR,
        "Citrate buffer; no concern.", "EU authorisation without ADI."),
    AdditiveInfo("E460", listOf("cellulose", "cellulose microcristalline", "microcrystalline cellulose"), AdditiveTier.THREE, AdditiveCategory.THICKENER,
        "Plant-fibre derivative; EFSA reaffirmed safety.", "EFSA 2018;16(1):5047."),
    AdditiveInfo("E509", listOf("chlorure de calcium", "calcium chloride"), AdditiveTier.THREE, AdditiveCategory.STABILIZER,
        "Firming agent; no concern.", "EU Regulation 1333/2008 (quantum satis)."),
    AdditiveInfo("E575", listOf("glucono-delta-lactone", "glucono delta lactone", "gdl"), AdditiveTier.THREE, AdditiveCategory.ACIDULANT,
        "Slow-release acidulant used in baked goods.", "EU authorisation without ADI."),
    AdditiveInfo("E965", listOf("maltitol", "sirop de maltitol"), AdditiveTier.THREE, AdditiveCategory.SWEETENER,
        "Sugar alcohol; moderate glycemic impact; laxative above tolerance.", "EFSA 2011 polyol opinion."),
    AdditiveInfo("E967", listOf("xylitol"), AdditiveTier.THREE, AdditiveCategory.SWEETENER,
        "Sugar alcohol; laxative above ~50 g.", "EFSA 2011 polyol opinion."),
    AdditiveInfo("E1422", listOf("amidon acétylé", "acetylated distarch adipate", "amidon modifié"), AdditiveTier.THREE, AdditiveCategory.THICKENER,
        "Modified starch; authorised without ADI.", "EU Regulation 1333/2008."),
    AdditiveInfo("E1442", listOf("phosphate de distarch hydroxypropyle", "hydroxypropyl distarch phosphate"), AdditiveTier.THREE, AdditiveCategory.THICKENER,
        "Modified starch; authorised without ADI.", "EU Regulation 1333/2008."),
    AdditiveInfo("E307", listOf("alpha-tocophérol", "alpha tocopherol", "tocopherols", "vitamine e (additif)"), AdditiveTier.THREE, AdditiveCategory.ANTIOXIDANT,
        "Vitamin E antioxidant; no concern.", "EFSA 2015;13(9):4247."),
    AdditiveInfo("E901", listOf("cire d'abeille", "beeswax"), AdditiveTier.THREE, AdditiveCategory.GLAZING_AGENT,
        "Glazing agent; not vegan.", "EFSA re-evaluated; no ADI specified."),
    AdditiveInfo("E920", listOf("l-cystéine", "l cysteine", "cystéine", "cysteine"), AdditiveTier.THREE, AdditiveCategory.FLOUR_TREATMENT,
        "Dough conditioner; often animal-derived (relevant for vegetarians/vegans).", "EU Regulation 1333/2008."),
)
