package fr.scanneat.domain.engine.scoring

// ============================================================================
// ADDITIVES DATABASE — Tier 2 (moderate concern) entries.
// Split out of AdditivesDb.kt; concatenated into ADDITIVES_DB there.
// Source citations preserved verbatim from the original TS engine.
// ============================================================================

internal val ADDITIVES_TIER2: List<AdditiveInfo> = listOf(
    AdditiveInfo("E338", listOf("acide phosphorique", "phosphoric acid"), AdditiveTier.TWO, AdditiveCategory.ACIDULANT,
        "Phosphate additive. Epidemiologic associations with cardiovascular/renal outcomes at high chronic intakes.",
        "EFSA Scientific Opinion on phosphates 2019;17(6):5674."),
    AdditiveInfo("E450", listOf("diphosphate", "pyrophosphate"), AdditiveTier.TWO, AdditiveCategory.STABILIZER,
        "Phosphate additive (same group as E338).", "EFSA 2019;17(6):5674."),
    AdditiveInfo("E451", listOf("triphosphate", "tripolyphosphate"), AdditiveTier.TWO, AdditiveCategory.STABILIZER,
        "Phosphate additive.", "EFSA 2019;17(6):5674."),
    AdditiveInfo("E452", listOf("polyphosphate"), AdditiveTier.TWO, AdditiveCategory.STABILIZER,
        "Phosphate additive.", "EFSA 2019;17(6):5674."),
    AdditiveInfo("E339", listOf("phosphate de sodium", "sodium phosphate"), AdditiveTier.TWO, AdditiveCategory.STABILIZER,
        "Phosphate additive.", "EFSA 2019;17(6):5674."),
    AdditiveInfo("E340", listOf("phosphate de potassium", "potassium phosphate"), AdditiveTier.TWO, AdditiveCategory.STABILIZER,
        "Phosphate additive.", "EFSA 2019;17(6):5674."),
    AdditiveInfo("E341", listOf("phosphate de calcium", "calcium phosphate"), AdditiveTier.TWO, AdditiveCategory.STABILIZER,
        "Phosphate additive.", "EFSA 2019;17(6):5674."),
    AdditiveInfo("E102", listOf("tartrazine", "jaune de tartrazine"), AdditiveTier.TWO, AdditiveCategory.COLORANT,
        "Azo dye. Hyperactivity/attention association in children; EU warning label required.",
        "McCann et al., The Lancet 370:1560 (2007); EU Regulation 1333/2008 Annex V."),
    AdditiveInfo("E110", listOf("jaune orangé s", "sunset yellow"), AdditiveTier.TWO, AdditiveCategory.COLORANT,
        "Azo dye. Southampton-study association; EU warning label.", "McCann et al. 2007; EU 1333/2008 Annex V."),
    AdditiveInfo("E122", listOf("azorubine", "carmoisine"), AdditiveTier.TWO, AdditiveCategory.COLORANT,
        "Azo dye. EU warning label.", "McCann et al. 2007; EU 1333/2008 Annex V."),
    AdditiveInfo("E124", listOf("ponceau 4r", "rouge cochenille a"), AdditiveTier.TWO, AdditiveCategory.COLORANT,
        "Azo dye. EU warning label.", "McCann et al. 2007; EU 1333/2008 Annex V."),
    AdditiveInfo("E129", listOf("rouge allura", "allura red"), AdditiveTier.TWO, AdditiveCategory.COLORANT,
        "Azo dye. EU warning label.", "McCann et al. 2007; EU 1333/2008 Annex V."),
    AdditiveInfo("E104", listOf("jaune de quinoléine", "quinoline yellow"), AdditiveTier.TWO, AdditiveCategory.COLORANT,
        "Quinophthalone dye; EU warning label.", "McCann et al. 2007; EU 1333/2008 Annex V."),
    AdditiveInfo("E127", listOf("érythrosine", "erythrosine"), AdditiveTier.TWO, AdditiveCategory.COLORANT,
        "Iodine-containing dye; thyroid concerns at high intakes.", "EFSA Re-evaluation 2011;9(1):1854."),
    AdditiveInfo("E173", listOf("aluminium"), AdditiveTier.TWO, AdditiveCategory.COLORANT,
        "Aluminium metallic colorant; neurotoxicity TWI.", "EFSA 2008;754 (TWI 1 mg/kg bw/week)."),
    AdditiveInfo("E150", listOf("colorant caramel"), AdditiveTier.TWO, AdditiveCategory.COLORANT,
        "Caramel, sub-class unspecified; most commercial caramel in dark sodas is E150c/d (4-MEI, IARC 2B).",
        "IARC Vol 101 (2013); EFSA 2011;9(3):2004."),
    AdditiveInfo("E150c", listOf("e150c", "caramel ammoniacal", "ammonia caramel"), AdditiveTier.TWO, AdditiveCategory.COLORANT,
        "4-methylimidazole (4-MEI) formation; IARC Group 2B.", "IARC Vol 101 (2013); EFSA 2011;9(3):2004."),
    AdditiveInfo("E150d", listOf("e150d", "caramel sulfite-ammoniacal", "sulfite-ammonia caramel"), AdditiveTier.TWO, AdditiveCategory.COLORANT,
        "Same 4-MEI concern as E150c; most common in dark sodas.", "IARC Vol 101 (2013); EFSA 2011;9(3):2004."),
    AdditiveInfo("E320", listOf("bha", "butylhydroxyanisol"), AdditiveTier.TWO, AdditiveCategory.ANTIOXIDANT,
        "IARC Group 2B (possibly carcinogenic, rodent forestomach tumours).",
        "IARC Monograph Vol 40 (1986); EFSA ADI 1 mg/kg bw/day reaffirmed 2011."),
    AdditiveInfo("E321", listOf("bht", "butylhydroxytoluène"), AdditiveTier.TWO, AdditiveCategory.ANTIOXIDANT,
        "Synthetic antioxidant; low EFSA ADI on developmental/reproductive grounds.",
        "EFSA Scientific Opinion 2012;10(3):2588."),
    AdditiveInfo("E951", listOf("aspartame"), AdditiveTier.TWO, AdditiveCategory.SWEETENER,
        "IARC Group 2B (possibly carcinogenic, 2023). Contraindicated in phenylketonuria.",
        "IARC Monograph Vol 134 (2023); JECFA 2023; EFSA ADI 40 mg/kg bw/day (2013)."),
    AdditiveInfo("E950", listOf("acésulfame-k", "acesulfame de potassium", "acesulfame potassium"), AdditiveTier.TWO, AdditiveCategory.SWEETENER,
        "Non-nutritive sweetener; mixed long-term metabolic evidence.", "EFSA Re-evaluation 2000 ADI 9 mg/kg bw/day."),
    AdditiveInfo("E955", listOf("sucralose"), AdditiveTier.TWO, AdditiveCategory.SWEETENER,
        "Decomposes at high temperatures; microbiome/glucose-response changes.", "EFSA 2000; Suez et al., Cell 2022."),
    AdditiveInfo("E954", listOf("saccharine", "saccharin"), AdditiveTier.TWO, AdditiveCategory.SWEETENER,
        "Legacy rat bladder-tumour data; IARC Group 3 (1999).", "IARC Vol 73 (1999); EFSA Re-evaluation 2018."),
    AdditiveInfo("E952", listOf("cyclamate", "cyclamate de sodium"), AdditiveTier.TWO, AdditiveCategory.SWEETENER,
        "Banned in the US (1969); authorised in EU within ADI.", "EFSA Re-evaluation 2000; FDA ban 21 CFR 189.135."),
    AdditiveInfo("E968", listOf("érythritol", "erythritol"), AdditiveTier.TWO, AdditiveCategory.SWEETENER,
        "Higher plasma erythritol linked to major adverse cardiovascular events (prospective cohort); causality debated.",
        "Witkowski et al., Nature Medicine 29:710 (2023); EFSA 2023;21(12):8430."),
    AdditiveInfo("E211", listOf("benzoate de sodium", "sodium benzoate"), AdditiveTier.TWO, AdditiveCategory.PRESERVATIVE,
        "Can react with vitamin C to form trace benzene.", "Gardner & Lawrence, J Food Prot 2007; EFSA 2016;14(3):4433."),
    AdditiveInfo("E212", listOf("benzoate de potassium", "potassium benzoate"), AdditiveTier.TWO, AdditiveCategory.PRESERVATIVE,
        "Same benzene-formation pathway as E211.", "EFSA 2016;14(3):4433."),
    AdditiveInfo("E210", listOf("acide benzoïque", "benzoic acid"), AdditiveTier.TWO, AdditiveCategory.PRESERVATIVE,
        "Parent of E211/E212; same benzene-formation pathway.", "Gardner & Lawrence 2007; EFSA 2016;14(3):4433."),
    AdditiveInfo("E475", listOf("esters polyglycériques d'acides gras", "polyglycerol esters of fatty acids"), AdditiveTier.TWO, AdditiveCategory.EMULSIFIER,
        "Synthetic emulsifier; class-level microbiome concern (extrapolated caution).", "EFSA 2017;15(12):5089."),
    AdditiveInfo("E905", listOf("cire microcristalline", "microcrystalline wax", "petroleum wax"), AdditiveTier.TWO, AdditiveCategory.GLAZING,
        "Petroleum-derived; MOSH/MOAH migration concern.", "EFSA 2012;10(6):2704; EFSA update 2023;21(9):8215."),
    AdditiveInfo("E1520", listOf("propylène glycol", "propylene glycol"), AdditiveTier.TWO, AdditiveCategory.SOLVENT,
        "Humectant/solvent; low EFSA ADI; narrowly restricted.", "EFSA 2018;16(4):5235."),
)
