package fr.scanneat.domain.engine.medication

// ============================================================================
// DRUG FACTS — split out of MedicationSubstanceDb.kt: one neutral,
// Wikipedia-sourced fact per active substance (fr/en article's own opening
// sentence, same bulk-fetch method as IngredientFactsDb — fetched
// 2026-07-13, re-verifiable against the live article).
// ============================================================================

internal data class DrugFact(
    val keys: List<String>,
    val factFr: String,
    val factEn: String,
)

internal val DRUG_FACTS: List<DrugFact> = listOf(
    DrugFact(listOf("paracetamol"),
        "Le paracétamol, aussi appelé acétaminophène, est un composé chimique utilisé comme antalgique (anti-douleur) et antipyrétique (anti-fièvre), qui figure depuis le début des années 1950 parmi les médicaments les plus communément utilisés et prescrits au monde.",
        "Paracetamol, or acetaminophen, is an analgesic and antipyretic agent used to treat fever and mild to moderate pain."),
    DrugFact(listOf("ibuprofene"),
        "Ibuprofène est la dénomination commune internationale de l'acide 2-[4-(2-méthyl)propyl]phénylpropanoïque.",
        "Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) that is used to relieve pain, fever, and inflammation."),
    DrugFact(listOf("hydrochlorothiazide"),
        "L'hydrochlorothiazide est une molécule utilisée comme médicament diurétique de la classe des thiazidiques.",
        "Hydrochlorothiazide, sold under the brand name Hydrodiuril among others, is a diuretic medication used to treat hypertension and swelling due to fluid build-up."),
    DrugFact(listOf("amlodipine"),
        "Le bésylate d'amlodipine est un antagoniste des canaux calciques de type L à longue action, utilisé comme antihypertenseur et pour le traitement de l'angine de poitrine.",
        "Amlodipine, sold under the brand name Norvasc, Copine among others, is a calcium channel blocker medication used to treat high blood pressure, coronary artery disease (CAD) and variant angina."),
    DrugFact(listOf("atorvastatine", "atorvastatin"),
        "L'atorvastatine est un médicament de type statine utilisé pour son action hypocholestérolémiante.",
        "Atorvastatin, sold under the brand name Lipitor among others, is a statin medication used to prevent cardiovascular disease in those at high risk and to treat abnormal lipid levels."),
    DrugFact(listOf("rosuvastatine"),
        "La rosuvastatine appartient au groupes des médicaments appelés statines, utilisées dans les dyslipidémies pour modifier les concentrations de choléstérol dans le sang.",
        "Rosuvastatin, sold under the brand name Crestor among others, is a statin medication, used to prevent cardiovascular disease in those at high risk and treat dyslipidemia or hyperlipidemia."),
    DrugFact(listOf("simvastatine"),
        "La simvastatine est une statine, c’est-à-dire un inhibiteur puissant de l'enzyme hydroxyméthylglutaryl CoA réductase — ou HMG-CoA réductase —.",
        "Simvastatin, sold under the brand name Zocor among others, is a statin, a type of lipid-lowering medication."),
    DrugFact(listOf("ezetimibe", "ézétimibe"),
        "L’ézétimibe est un médicament utilisé dans le traitement des hypercholestérolémies et agissant en diminuant l'absorption du cholestérol ingéré par le tube digestif.",
        "Ezetimibe, sold under the brand name Zetia among others, is a medication used to treat high blood cholesterol and certain other lipid abnormalities."),
    DrugFact(listOf("valsartan"),
        "Le valsartan est une molécule utilisée comme médicament par voie orale, antagoniste des récepteurs de l'angiotensine II.",
        "Valsartan, sold under the brand name Diovan among others, is a medication used to treat high blood pressure, heart failure, and diabetic kidney disease."),
    DrugFact(listOf("candesartan", "candésartan"),
        "Le candésartan est un antihypertenseur qui appartient à la famille des antagonistes des récepteurs de l'angiotensine II.",
        "Candesartan is an angiotensin receptor blocker (ARB) primarily used to treat high blood pressure and congestive heart failure."),
    DrugFact(listOf("irbesartan", "irbésartan"),
        "L'irbésartan est un antihypertenseur qui appartient à la famille des antagonistes des récepteurs de l'angiotensine II.",
        "Irbesartan, sold under the brand name Aprovel among others, is a medication used to treat hypertension, heart failure, and diabetic kidney disease."),
    DrugFact(listOf("losartan"),
        "Le losartan est un antihypertenseur qui appartient à la famille des antagonistes des récepteurs de l'angiotensine II.",
        "Losartan, sold under the brand name Cozaar among others, is a medication used to treat high blood pressure (hypertension)."),
    DrugFact(listOf("telmisartan"),
        "Le telmisartan est un des antagonistes des récepteurs de l'angiotensine II et est utilisé comme antihypertenseur.",
        "Telmisartan, sold under the brand name Micardis among others, is a medication used to treat high blood pressure and heart failure."),
    DrugFact(listOf("tramadol"),
        "Le tramadol est un analgésique central développé par la firme allemande Grünenthal GmbH (en) dans les années 1970.",
        "Tramadol, sold under the brand name Tramal among others, is an opioid pain medication and a serotonin–norepinephrine reuptake inhibitor (SNRI) used to treat moderate to severe pain."),
    DrugFact(listOf("oxycodone"),
        "L'oxycodone, dihydrohydroxycodéinone, ou dihydro-oxycodéinone, est un antalgique stupéfiant très puissant dérivé de la thébaïne.",
        "Oxycodone, sold under the brand names Roxicodone and OxyContin among others, is a semi-synthetic opioid used medically for the treatment of moderate to severe pain."),
    DrugFact(listOf("fentanyl"),
        "Le fentanyl, appelé aussi apache ou dance fever, est une drogue à propriété analgésique opioïde, synthétisée pour la première fois par le docteur Paul Janssen en Belgique vers la fin des années 1950.",
        "Fentanyl is a highly potent synthetic opioid of the piperidine family, used primarily as pain medication."),
    DrugFact(listOf("metformine"),
        "La metformine est un antidiabétique oral de la famille des biguanides normoglycémiants utilisé en première intention dans le traitement du diabète de type 2. Son rôle est de diminuer l'insulino-résistance de l'organisme intolérant aux glucides et de diminuer la néoglucogenèse hépatique.",
        "Metformin, sold under the brand name Glucophage, among others, is the main first-line medication for the treatment of type 2 diabetes, particularly in people who are overweight."),
    DrugFact(listOf("ramipril"),
        "Le ramipril est une molécule utilisée comme antihypertenseur de la famille des inhibiteurs de l'enzyme de conversion.",
        "Ramipril, sold under the brand name Altace among others, is an ACE inhibitor type medication used to treat high blood pressure, heart failure, and diabetic kidney disease."),
    DrugFact(listOf("perindopril", "périndopril"),
        "Le périndopril est un inhibiteur de l'enzyme de conversion de l’angiotensine (IEC).",
        "Perindopril is a medication used to treat high blood pressure, heart failure, or stable coronary artery disease."),
    DrugFact(listOf("amoxicilline"),
        "L'amoxicilline est un antibiotique β-lactamine bactéricide de la famille des aminopénicillines indiqué dans le traitement des infections bactériennes à germes sensibles.",
        "Amoxicillin is an antibiotic medication belonging to the aminopenicillin class of the penicillin family."),
    DrugFact(listOf("levothyroxine", "lévothyroxine"),
        "La lévothyroxine, aussi connue sous le nom de L-thyroxine, T4 synthétique ou 3,5,3',5'-tetraiodo-L-thyronine, est une forme synthétique de la thyroxine, également utilisée comme médicament.",
        "Levothyroxine, also known as L-thyroxine, is a synthetic form of the thyroid hormone thyroxine (T4)."),
    DrugFact(listOf("escitalopram"),
        "L'escitalopram, commercialisé dans divers pays sous les noms de Lexapro, Cipralex, Sipralexa et Seroplex, est un antidépresseur inhibiteur sélectif de la recapture de la sérotonine.",
        "Escitalopram, sold under the brand names Lexapro and Cipralex, among others, is an antidepressant medication of the selective serotonin reuptake inhibitor (SSRI) class."),
    DrugFact(listOf("olanzapine"),
        "L'olanzapine (DCI) est un antipsychotique de seconde génération appartenant à la classe des thiénobenzodiazépines employé principalement pour traiter la schizophrénie et le trouble bipolaire.",
        "Olanzapine, sold under the brand name Zyprexa among others, is an atypical antipsychotic primarily used to treat schizophrenia and bipolar disorder."),
    DrugFact(listOf("risperidone", "rispéridone"),
        "La rispéridone est un antipsychotique de seconde génération, appartenant à la classe des benzisoxazoles, commercialisé principalement sous le nom Risperdal.",
        "Risperidone, sold under the brand name Risperdal among others, is an atypical antipsychotic used to treat schizophrenia and bipolar disorder, as well as aggressive and self-injurious behaviors associated with autism spectrum disorder."),
    DrugFact(listOf("aripiprazole"),
        "L'aripiprazole (DCI) est un médicament antipsychotique de troisième génération.",
        "Aripiprazole, sold under the brand name Abilify, among others, is a unique atypical antipsychotic primarily used in the treatment of schizophrenia, mania in bipolar disorder, and irritability associated with autism spectrum disorder; other uses include as an add-on treatment for major depressive disorder, obsessive–compulsive disorder, and tic disorders."),
    DrugFact(listOf("gabapentine"),
        "La gabapentine, molécule dérivé de l'acide γ-aminobutyrique, est un médicament commercialisé sous le nom commercial de Neurontin ou génériques.",
        "Gabapentin, sold under the brand name Neurontin among others, is an anticonvulsant medication used to treat neuropathic pain and partial seizures of epilepsy."),
    DrugFact(listOf("pregabaline", "prégabaline"),
        "La prégabaline est un médicament utilisé, de manière principale, dans le traitement des douleurs neuropathiques et des crises d'épilepsie partielles.",
        "Pregabalin, sold under the brand names Axalid and Lyrica among others, is an anticonvulsant, analgesic, and anxiolytic amino acid medication used to treat epilepsy, neuropathic pain, fibromyalgia, restless legs syndrome, opioid withdrawal, generalized anxiety disorder (GAD), and postherpetic neuralgia."),
    DrugFact(listOf("rivaroxaban"),
        "Le rivaroxaban est un médicament anticoagulant oral direct, inhibiteur du facteur Xa de la famille des oxazolidinones.",
        "Rivaroxaban, sold under the brand name Xarelto among others, is an anticoagulant medication used to treat and reduce the risk of blood clots."),
    DrugFact(listOf("budesonide", "budésonide"),
        "Le budésonide est un médicament anti-inflammatoire (glucocorticoïde) utilisé entre autres pour le traitement de l'asthme, la rhinite non infectieuse et pour le traitement et la prévention des polypes nasaux.",
        "Budesonide, sold under the brand name Pulmicort, among others, is a steroid medication."),
    DrugFact(listOf("fluticasone"),
        "La fluticasone est un anti-inflammatoire stéroïdien de la famille des glucocorticoïdes.",
        "Fluticasone propionate, sold under the brand names Flovent and Flonase among others, is a glucocorticoid steroid medication."),
    DrugFact(listOf("pantoprazole"),
        "Le pantoprazole est un médicament gastro-résistant qui réduit la quantité d'acide sécrétée par l'estomac.",
        "Pantoprazole, sold under the brand name Protonix, among others, is a medication used for the treatment of stomach ulcers, short-term treatment of erosive esophagitis due to gastroesophageal reflux disease (GERD), maintenance of healing of erosive esophagitis, and pathological hypersecretory conditions including Zollinger–Ellison syndrome."),
    DrugFact(listOf("tadalafil"),
        "Le tadalafil est une molécule indolique, dérivée de base azotée de la famille des inhibiteurs de la phosphodiestérase de type 5 (PDE5), utilisée dans le traitement des troubles de l'érection.",
        "Tadalafil, sold under the brand name Cialis among others, is a medication used to treat erectile dysfunction, benign prostatic hyperplasia, and pulmonary arterial hypertension."),
    DrugFact(listOf("sildenafil", "sildénafil"),
        "Le citrate de sildénafil est un médicament de la classe des inhibiteurs de la phosphodiestérase de type 5 (PDE5) développé par la firme pharmaceutique Pfizer.",
        "Sildenafil, sold under the brand name Viagra among others, is a medication used to treat erectile dysfunction and pulmonary arterial hypertension."),
    DrugFact(listOf("cholecalciferol", "cholécalciférol"),
        "Le cholécalciférol est une forme de vitamine D, également appelée vitamine D3. Son nom systématique est « (3β,5Z,7E)-9,10-sécocholesta-5,7,10(19)-triène-3-ol ». La vitamine D3 est un sécostéroïde plutôt parent de la testostérone, du cholestérol et du cortisol.",
        "Cholecalciferol, also known as vitamin D3, colecalciferol or calciol, is a skin-made vitamin D that is found in certain foods and used as a dietary supplement."),
    DrugFact(listOf("aciclovir"),
        "L'aciclovir (DCI) ou acyclovir commercialisé sous les noms de Zovirax, Activir ou Aciclovir, est l'un des principaux médicaments antiviraux.",
        "Aciclovir, also known as acyclovir, is an antiviral medication."),
    DrugFact(listOf("bisoprolol"),
        "Le bisoprolol est une molécule de la classe des bêta-bloquants, utilisée pour traiter l'arythmie cardiaque, la tachycardie, l'angine de poitrine, etc.",
        "Bisoprolol, sold under the brand name Zebeta among others, is a beta blocker which is selective for the beta-1 receptor and used for cardiovascular diseases, including tachyarrhythmias, high blood pressure, angina, and heart failure."),
    DrugFact(listOf("indapamide"),
        "L'indapamide est un médicament, de type diurétique, utilisé[Où ?] pour traiter l'hypertension artérielle ou certains œdèmes[évasif].",
        "Indapamide is a thiazide-like diuretic drug used in the treatment of hypertension, as well as decompensated heart failure."),
)
