package fr.scanneat.domain.engine.planning

// ============================================================================
// CURATED PAIRINGS — hand-authored, not from the Ahn et al. flavor-network
// dataset (PairingsDataAtoC/CtoL/LtoR/RtoZ.kt's source). Added for ingredients
// with no entry at all in that dataset (checked against every produce name in
// SeasonalProduceDb.kt: ~40% resolved to zero suggestions before this file).
// Each entry lists genuinely well-established, classic pairings (French home
// cooking / bistro repertoire) rather than raw co-occurrence counts - the
// `cooccur` field here is a hand-set descending relative-strength rank
// (90 = the single most classic pairing for that ingredient down to 20), not
// a real recipe-corpus count, and each PairingsResult's `recipeCount` is 0 to
// mark it as curated rather than corpus-derived for any future caller that
// inspects it via matchPairings().
// ============================================================================

internal val PAIRINGS_CURATED: Map<String, PairingsResult> = mapOf(
    "nectarine" to PairingsResult("nectarine", "nectarine", 0, listOf(
        PairingEntry("almond", "amandes", 90),
        PairingEntry("vanilla", "vanille", 80),
        PairingEntry("raspberry", "framboise", 70),
        PairingEntry("honey", "miel", 60),
        PairingEntry("mint", "menthe", 50),
        PairingEntry("basil", "basilic", 40),
        PairingEntry("ginger", "gingembre", 30),
        PairingEntry("cream", "crème", 20),
    )),
    "plum" to PairingsResult("plum", "prune", 0, listOf(
        PairingEntry("cinnamon", "cannelle", 90),
        PairingEntry("almond", "amandes", 80),
        PairingEntry("vanilla", "vanille", 70),
        PairingEntry("star_anise", "anis étoilé", 60),
        PairingEntry("red_wine", "vin rouge", 50),
        PairingEntry("ginger", "gingembre", 40),
        PairingEntry("orange", "orange", 30),
        PairingEntry("honey", "miel", 20),
    )),
    "currant" to PairingsResult("currant", "groseille", 0, listOf(
        PairingEntry("vanilla", "vanille", 90),
        PairingEntry("cream", "crème", 80),
        PairingEntry("raspberry", "framboise", 70),
        PairingEntry("lemon", "citron", 60),
        PairingEntry("mint", "menthe", 50),
        PairingEntry("orange", "orange", 40),
        PairingEntry("honey", "miel", 30),
        PairingEntry("sugar", "sucre", 20),
    )),
    "rhubarb" to PairingsResult("rhubarb", "rhubarbe", 0, listOf(
        PairingEntry("strawberry", "fraise", 90),
        PairingEntry("vanilla", "vanille", 80),
        PairingEntry("ginger", "gingembre", 70),
        PairingEntry("orange", "orange", 60),
        PairingEntry("cinnamon", "cannelle", 50),
        PairingEntry("cream", "crème", 40),
        PairingEntry("honey", "miel", 30),
        PairingEntry("sugar", "sucre", 20),
    )),
    "kiwi" to PairingsResult("kiwi", "kiwi", 0, listOf(
        PairingEntry("strawberry", "fraise", 90),
        PairingEntry("lime", "citron vert", 80),
        PairingEntry("mint", "menthe", 70),
        PairingEntry("honey", "miel", 60),
        PairingEntry("banana", "banane", 50),
        PairingEntry("coconut", "noix de coco", 40),
        PairingEntry("orange", "orange", 30),
        PairingEntry("vanilla", "vanille", 20),
    )),
    "clementine" to PairingsResult("clementine", "clémentine", 0, listOf(
        PairingEntry("cocoa", "cacao", 90),
        PairingEntry("cinnamon", "cannelle", 80),
        PairingEntry("star_anise", "anis étoilé", 70),
        PairingEntry("almond", "amandes", 60),
        PairingEntry("honey", "miel", 50),
        PairingEntry("ginger", "gingembre", 40),
        PairingEntry("vanilla", "vanille", 30),
        PairingEntry("walnut", "noix", 20),
    )),
    "eggplant" to PairingsResult("eggplant", "aubergine", 0, listOf(
        PairingEntry("tomato", "tomate", 90),
        PairingEntry("garlic", "ail", 80),
        PairingEntry("olive_oil", "huile d'olive", 70),
        PairingEntry("basil", "basilic", 60),
        PairingEntry("parmesan_cheese", "parmesan", 50),
        PairingEntry("mozzarella_cheese", "mozzarella", 40),
        PairingEntry("oregano", "origan", 30),
        PairingEntry("mint", "menthe", 20),
    )),
    "spinach" to PairingsResult("spinach", "épinard", 0, listOf(
        PairingEntry("garlic", "ail", 90),
        PairingEntry("lemon", "citron", 80),
        PairingEntry("nutmeg", "muscade", 70),
        PairingEntry("feta_cheese", "feta", 60),
        PairingEntry("egg", "œuf", 50),
        PairingEntry("walnut", "noix", 40),
        PairingEntry("olive_oil", "huile d'olive", 30),
        PairingEntry("parmesan_cheese", "parmesan", 20),
    )),
    "arugula" to PairingsResult("arugula", "roquette", 0, listOf(
        PairingEntry("parmesan_cheese", "parmesan", 90),
        PairingEntry("lemon", "citron", 80),
        PairingEntry("olive_oil", "huile d'olive", 70),
        PairingEntry("walnut", "noix", 60),
        PairingEntry("fig", "figue", 50),
        PairingEntry("ham", "jambon", 40),
        PairingEntry("balsamic_vinegar", "vinaigre balsamique", 30),
        PairingEntry("black_pepper", "poivre noir", 20),
    )),
    "broad_bean" to PairingsResult("broad_bean", "fève", 0, listOf(
        PairingEntry("mint", "menthe", 90),
        PairingEntry("lemon", "citron", 80),
        PairingEntry("olive_oil", "huile d'olive", 70),
        PairingEntry("garlic", "ail", 60),
        PairingEntry("parmesan_cheese", "parmesan", 50),
        PairingEntry("bacon", "bacon", 40),
        PairingEntry("thyme", "thym", 30),
        PairingEntry("black_pepper", "poivre noir", 20),
    )),
    "green_bean" to PairingsResult("green_bean", "haricot vert", 0, listOf(
        PairingEntry("garlic", "ail", 90),
        PairingEntry("almond", "amandes", 80),
        PairingEntry("lemon", "citron", 70),
        PairingEntry("butter", "beurre", 60),
        PairingEntry("olive_oil", "huile d'olive", 50),
        PairingEntry("shallot", "échalote", 40),
        PairingEntry("bacon", "bacon", 30),
        PairingEntry("black_pepper", "poivre noir", 20),
    )),
    "white_bean" to PairingsResult("white_bean", "haricot blanc", 0, listOf(
        PairingEntry("garlic", "ail", 90),
        PairingEntry("rosemary", "romarin", 80),
        PairingEntry("olive_oil", "huile d'olive", 70),
        PairingEntry("tomato", "tomate", 60),
        PairingEntry("sage", "sauge", 50),
        PairingEntry("onion", "oignon", 40),
        PairingEntry("thyme", "thym", 30),
        PairingEntry("black_pepper", "poivre noir", 20),
    )),
    "brussels_sprouts" to PairingsResult("brussels_sprouts", "chou de Bruxelles", 0, listOf(
        PairingEntry("bacon", "bacon", 90),
        PairingEntry("balsamic_vinegar", "vinaigre balsamique", 80),
        PairingEntry("garlic", "ail", 70),
        PairingEntry("parmesan_cheese", "parmesan", 60),
        PairingEntry("walnut", "noix", 50),
        PairingEntry("maple_syrup", "sirop d'érable", 40),
        PairingEntry("black_pepper", "poivre noir", 30),
        PairingEntry("olive_oil", "huile d'olive", 20),
    )),
    "endive" to PairingsResult("endive", "endive", 0, listOf(
        PairingEntry("blue_cheese", "fromage bleu", 90),
        PairingEntry("walnut", "noix", 80),
        PairingEntry("apple", "pomme", 70),
        PairingEntry("orange", "orange", 60),
        PairingEntry("ham", "jambon", 50),
        PairingEntry("mustard", "moutarde", 40),
        PairingEntry("black_pepper", "poivre noir", 30),
        PairingEntry("olive_oil", "huile d'olive", 20),
    )),
    "jerusalem_artichoke" to PairingsResult("jerusalem_artichoke", "topinambour", 0, listOf(
        PairingEntry("garlic", "ail", 90),
        PairingEntry("thyme", "thym", 80),
        PairingEntry("parmesan_cheese", "parmesan", 70),
        PairingEntry("cream", "crème", 60),
        PairingEntry("walnut", "noix", 50),
        PairingEntry("nutmeg", "muscade", 40),
        PairingEntry("olive_oil", "huile d'olive", 30),
        PairingEntry("bacon", "bacon", 20),
    )),
    "parsnip" to PairingsResult("parsnip", "panais", 0, listOf(
        PairingEntry("honey", "miel", 90),
        PairingEntry("thyme", "thym", 80),
        PairingEntry("nutmeg", "muscade", 70),
        PairingEntry("butter", "beurre", 60),
        PairingEntry("carrot", "carotte", 50),
        PairingEntry("maple_syrup", "sirop d'érable", 40),
        PairingEntry("black_pepper", "poivre noir", 30),
        PairingEntry("garlic", "ail", 20),
    )),
    "turnip" to PairingsResult("turnip", "navet", 0, listOf(
        PairingEntry("butter", "beurre", 90),
        PairingEntry("thyme", "thym", 80),
        PairingEntry("black_pepper", "poivre noir", 70),
        PairingEntry("carrot", "carotte", 60),
        PairingEntry("honey", "miel", 50),
        PairingEntry("nutmeg", "muscade", 40),
        PairingEntry("cream", "crème", 30),
        PairingEntry("garlic", "ail", 20),
    )),
    "butternut_squash" to PairingsResult("butternut_squash", "courge butternut", 0, listOf(
        PairingEntry("sage", "sauge", 90),
        PairingEntry("nutmeg", "muscade", 80),
        PairingEntry("cinnamon", "cannelle", 70),
        PairingEntry("maple_syrup", "sirop d'érable", 60),
        PairingEntry("garlic", "ail", 50),
        PairingEntry("parmesan_cheese", "parmesan", 40),
        PairingEntry("black_pepper", "poivre noir", 30),
        PairingEntry("olive_oil", "huile d'olive", 20),
    )),
)
